import './globals.css'
import { useContext } from 'react'
import AuthContext from './Helper/AuthContext'
import BaseHeader from './Components/BaseHeader'
import UnAuthenticatedHeader from './pages/un-authenticated-header'


export const metadata = {
  title: 'Codehub',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const AuthStatus = typeof window !== 'undefined' ? useContext(AuthContext) : null;
  return (
    <AuthContext>
      <html lang="en">
        <body>
          { AuthStatus && AuthStatus.authenticationStatus ? (
            <BaseHeader/>
          ) : (
            <UnAuthenticatedHeader/>
          ) }
          <div>
            {children}
          </div>
        </body>
      </html>
    </AuthContext>
    
  )
}
