import './globals.css'
import { Providers } from './providers'


export const metadata = {
  title: 'Codehub',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      {/* <head><script src="http://localhost:8097"></script></head> */}
      <Providers>
        <body>{children}</body>
      </Providers>
    </html>
  );
}
